name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Enable Corepack
      run: corepack enable

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
        
    - name: Install dependencies
      run: |
        yarn set version 4.9.1
        yarn config set nodeLinker node-modules
        yarn config set checksumBehavior update
        yarn install --mode skip-build
      env:
        YARN_ENABLE_HARDENED_MODE: 1
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
      
    - name: Run tests
      run: yarn test 